export const GetQueryTypes = () => {
  return [
    { queryType: "AgentRestorePoint", cameleCase: 'agentRestorePoint' },
    { queryType: "AgentBackupJob", cameleCase: 'agentBackupJob' },
    { queryType: "AgentProtectionGroup", cameleCase: 'agentProtectionGroup' },
    { queryType: "DiscoveredComputer", cameleCase: 'discoveredComputer' },
    { queryType: "BackupServer", cameleCase: 'backupServer' },
    { queryType: "Repository", cameleCase: 'repository' },
    { queryType: "Job", cameleCase: 'job' },
    { queryType: "Backup", cameleCase: 'backup' },
    { queryType: "BackupFile", cameleCase: 'backupFile' },
    { queryType: "FailoverPlan", cameleCase: 'failoverPlan' },
    { queryType: "RestorePoint", cameleCase: 'restorePoint' },
    { queryType: "VmRestorePoint", cameleCase: 'vmRestorePoint' },
    { queryType: "vAppRestorePoint", cameleCase: 'vAppRestorePoint' },
    { queryType: "Replica", cameleCase: 'replica' },
    { queryType: "VmReplicaPoint", cameleCase: 'vmReplicaPoint' },
    { queryType: "HierarchyRoot", cameleCase: 'hierarchyRoot' },
    { queryType: "ManagedServer", cameleCase: 'managedServer' },
    { queryType: "BackupJobSession", cameleCase: 'backupJobSession' },
    { queryType: "ReplicaJobSession", cameleCase: 'replicaJobSession' },
    { queryType: "RestoreSession", cameleCase: 'restoreSession' },
    { queryType: "BackupTaskSession", cameleCase: 'backupTaskSession' },
    { queryType: "ReplicaTaskSession", cameleCase: 'replicaTaskSession' },
    { queryType: "WanAccelerator", cameleCase: 'wanAccelerator' },
    { queryType: "VCloudOrganizationConfig", cameleCase: 'vCloudOrganizationConfig' },
    { queryType: "VsphereSelfServiceConfig", cameleCase: 'vsphereSelfServiceConfig' },
    { queryType: "CloudGateway", cameleCase: 'cloudGateway' },
    { queryType: "CloudGatewayPool", cameleCase: 'cloudGatewayPool' },
    { queryType: "CloudTenant", cameleCase: 'cloudTenant' },
    { queryType: "CloudSubtenant", cameleCase: 'cloudSubtenant' },
    { queryType: "CloudHardwarePlan", cameleCase: 'cloudHardwarePlan' },
    { queryType: "CloudPublicIpAddress", cameleCase: 'cloudPublicIpAddress' },
    { queryType: "CloudFailoverPlan", cameleCase: 'cloudFailoverPlan' },
    { queryType: "CloudVmReplicaPoint", cameleCase: 'cloudVmReplicaPoint' },
    { queryType: "CloudReplica", cameleCase: 'cloudReplica' },
    { queryType: "VlanConfiguration", cameleCase: 'vlanConfiguration' },
    { queryType: "CloudFailoverSession", cameleCase: 'cloudFailoverSession' },
    { queryType: "ObjectInJob", cameleCase: 'objectInJob' },
    { queryType: "Task", cameleCase: 'task' },
    { queryType: "Credentials", cameleCase: 'credentials' },
    { queryType: "Passwords", cameleCase: 'passwords' },
  ]
}
